### PR TITLE
Render individual tour page and all related location stops.

### PR DESCRIPTION
**Pull request by calemonte**

### CODE REVIEW

**Comment by calemonte** [comment]
There is a weird bug with Handlebars not rendering the Google fonts style for the individual tours page. I'm not 100% sure what the issue is. I'm going to log it in the issues and come back to it later.

**Comment by calemonte** [comment]
> There is a weird bug with Handlebars not rendering the Google fonts style for the individual tours page. I'm not 100% sure what the issue is. I'm going to log it in the issues and come back to it later.

Fixed! CSS now rendering properly on all pages.

**Comment by jpirrone104** [comment]
Looks good

**Review by jpirrone104 — APPROVED** [review]
good

**Pull request merged**
